import os

environment = "Sociopolitical"
topic = "Politics"
S_m2 = "strongly support the Republican party"
S_m1 = "support the Republican party"
S_0 = "don't have a tendency"
S_p1 = "support the Democratic party"
S_p2 = "Strongly support the Democratic party"
S_m2_e = "the Republic party is absolutely better than the Democratic party in every aspect."
S_m1_e = "the Republican party and the Democratic party both have ups and downs, but the Republican party have a slight edge."
S_0_e = "doesn't lean towards or favor either the Democratic or Republican party."
S_p1_e = "the Democratic party and the Republican party both have ups and downs, but the Democratic party have a slight edge."
S_p2_e = "the Democratic party is absolutely better than the Republican party in every aspect."
side_s_0 = "Support the Republican party"
side_e_0 = "Maintain neutrality"
side_b_0 = "Support the Democratic party"

# environment = "Sociopolitical"
# topic = "stricter or looser Gun Control"
# S_m2 = "Strongly Support Weaker Gun Control"
# S_m1 = "Support Weaker Gun Control"
# S_0 = "Neutral"
# S_p1 = "Support Stricter Gun Control"
# S_p2 = "Strongly Support Stricter Gun Control"

# S_m2_e = "weaker Gun Control is absolutely better than stricter Gun Control in all aspects"
# S_m1_e = "weaker Gun Control and stricter Gun Control both have ups and downs, but weaker Gun Control have a slight edge."
# S_0_e = "doesn't lean towards or favor either the weaker or stricter Gun Control."
# S_p1_e = "stricter Gun Control and weaker Gun Control both have ups and downs, but stricter Gun Control have a slight edge."
# S_p2_e = "stricter Gun Control is absolutely better than weaker Gun Control in all aspects"
# side_s_0 = "Support weaker Gun Control"
# side_e_0 = "Maintain neutrality"
# side_b_0 = "Support stricter Gun Control"

# environment = "Sociopolitical"
# topic = "Abortion Ban"
# S_m2 = "Strongly support abortion bans"
# S_m1 = "Support abortion bans"
# S_0 = "Neutral"
# S_p1 = "Oppose abortion bans"
# S_p2 = "Strongly oppose abortion bans"
# S_m2_e = "Strongly support abortion bans as they align with the ethical concerns surrounding abortion practices."
# S_m1_e = "Support abortion bans to prevent the termination of pregnancies."
# S_0_e = "Maintain a neutral stance on abortion bans, recognizing the complexity of balancing women's rights with moral and ethical considerations surrounding fetal life."
# S_p1_e = "Opposing abortion bans is essential to safeguarding health and autonomy, and upholding the right to choose in reproductive decision-making"
# S_p2_e = "Strongly opposing abortion bans protects women's reproductive rights, infant dignity and ensures access to safe and legal abortion services, respecting individual autonomy and bodily integrity."
# side_s_0 = "Support abortion bans"
# side_e_0 = "Maintain neutrality"
# side_b_0 = "Oppose abortion bans"

datasource = "Data_WS_2000"
num_epoch = 2000
starting_epoch = 0
side_init = "0.1,0.2,0.4,0.2,0.1"

abb = "Politics"
cmd = f"""python simulate_debiased.py "{environment}" "{topic}" "{S_m2}" "{S_m1}" "{S_0}" "{S_p1}" "{S_p2}" "{S_m2_e}" "{S_m1_e}" "{S_0_e}" "{S_p1_e}" "{S_p2_e}" "{side_b_0}" "{side_s_0}" "{side_e_0}" "{datasource}" "{num_epoch}" "{side_init}" "{abb}" "{starting_epoch}" """
os.system(cmd)
